### ISSUE TITLE
Notification deve ser ignorada

### ISSUE THREAD

**Issue by agcjunior** [balta-io/7182#1]
Ao herdar da classe Notifiable do Flunt é necessário ignorar a "Notification" no DbContext do EntityFramework. Ao tentar gerar uma Migration recebi o seguinte erro:

The relationship from 'Notification' to 'Email.Notifications' is not supported because the owned entity type 'Email' cannot be on the principal side of a non-ownership relationship.

O meu Email é um ValueObject que por sua vez herda de Notifiable:

public class Email : ValueObject
   {
        protected Email()
        { }

        public Email(string value)
        {
            AddNotifications(new Contract()
                .IsEmail(value, "Email", "Email inválido")
            );
            if (Valid)
                Value = value;
        }

        public string Value { get; private set; }

        protected override IEnumerable<object> GetAtomicValues()
        {
            yield return Value;
        }
    }

Para corrigir esse problema precisei ignorar a Notification no OnModelCreating do DbContext, veja:

`protected override void OnModelCreating(ModelBuilder modelBuilder()
 {
      modelBuilder.Ignore<Notification>();
 }`

**Comment by andrebaltieri** [comment]
@agcjunior muitíssimo obrigado pelo feedback!
Vai ajudar muito o pessoal <3
